describe('Secret Menu with Cypress Studio', () => {
  beforeEach(() => {
    cy.visit('/secret-menu');
  });

  it('does stuff generated by Cypress Studio', () => {});

  /* ==== Test Created with Cypress Studio ==== */
  it('filter kfc', function() {
    /* ==== Generateddescribe('Secret Menu with Cypress Studio', () => {
  beforeEach(() => {
    cy.visit('/secret-menu');
  });

  it('does stuff generated by Cypress Studio', () => {});

  /* ==== Test Created with Cypress Studio ==== */
    it('filter kfc', function() {
      /* ==== Generated with Cypress Studio ==== */
      cy.get('#restaurant-visibility-filter').select('KFC');
      cy.get(':nth-child(1) > .whereToOrder > .cell').should('have.text', 'KFC');
      /* ==== End Cypress Studio ==== */
    });
  });
  with Cypress Studio ==== */
    cy.get('#restaurant-visibility-filter').select('KFC');
    cy.get(':nth-child(1) > .whereToOrder > .cell').should('have.text', 'KFC');
    /* ==== End Cypress Studio ==== */
  });
});
